spring:
  profiles:
    group:
      "local": "local, common"
      "development": "development,common"
    active: local
---
# 공통
spring:
  config:
    activate:
      on-profile: "common"
  servlet: # 용량 늘려주는 설정
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

# s3에 필요한 정보
cloud:
  aws:
    credentials: # 엑세스, 시크릿 키
      access-key: AKIAUYOGGEALH3FIQQI2
      secret-key: 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
    region: # S3 지역
      static: ap-northeast-2
    s3: # 버킷이름
      bucket: ateco
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---
# 로컬 환경
spring:
  environment: "local"
  config:
    activate:
      on-profile: "local"
  file-dir: /src/main/resources/static/files/
---
# 배포 환경
spring:
  environment: "development"
  config:
    activate:
      on-profile: "development"
  file-dir: /home/ec2-user/files/
